### ISSUE TITLE
Compatibility with spectator mode

### ISSUE THREAD

**Issue by zedwick** [rolandoislas/multi-hotbar#13]
This mod doesn't seem to be compatible with Spectator mode, it replaces the spectate menu with my hotbar.

Easy to test, just switch to spectator mode and see your hotbar in place of the spectator menu :)

Tested using multihotbar-1.11.2-2.1.1-build-T19.

**Comment by zedwick** [comment]
Thanks! Spectator mode menu now works, however I could only see one hotbar otherwise. I had it set to '4' in the mod config. Changing it to 2 worked, as did changing it back to 4. So not a big problem, but had me confused for a minute there.

Thanks again for fixing it so quickly!

**Comment by rolandoislas** [comment]
The hotbar being set to one when connecting to a server was a bug that has been resolved in version 2.1.2.

**Comment by zedwick** [comment]
Ah, brilliant. Thank you!
