### ISSUE TITLE
Config Request: Stop main inventory row swapping when viewing chests

### ISSUE THREAD

**Issue by akanimh** [rolandoislas/multi-hotbar#17]
Version: 1.10.2

Great mod! If the cursor is in the second hotbar, and you view a chest it shows the current row in the hotbar, and puts your hotbars inventory in the top row. I see how that is something you can get used to but I'd prefer thinking of my hotbar as it's own stationary inventory row, and the top row of my inventory it's own hotbar, and so on. Is it possible to just show your default inventory arrangement no matter what hotbar you're working in when accessing the chest?

**Comment by rolandoislas** [comment]
It is a planned feature: #16.

**Comment by akanimh** [comment]
Ah thanks! I didn't realize that is what you meant.
