### ISSUE TITLE
Hotbars swaps inventory

### ISSUE THREAD

**Issue by NovaViper** [rolandoislas/multi-hotbar#22]
In 1.11.2, it seems that the mod swamps my inventory rows completely (the default row gets set behind the first row in the inventory or the second row inside the inventory is displayed instead of the first row). I haven't messed with any of the settings either, but it still occurs. Is this normal?

**Comment by rolandoislas** [comment]
See #16

**Comment by NovaViper** [comment]
I looked at it but I'm still confused on how to prevent the glitch

**Comment by NovaViper** [comment]
*Facepalm* I did some experimenting with the settings and figured out the purpose of the hotbar switching
