### ISSUE TITLE
1.12 server crashes after adding tinkers

### ISSUE THREAD

**Issue by parko12345** [rolandoislas/multi-hotbar#26]
[crash-2017-07-19_13.48.39-server.txt](https://github.com/rolandoislas/multi-hotbar/files/1159364/crash-2017-07-19_13.48.39-server.txt)

trying to understand why the server is crashing every time
any advice would help

thanks

**Comment by rolandoislas** [comment]
The crash is related to Tinkers' Construct. Multi-hotbar does not appear to be in the modlist.
