### ISSUE TITLE
Frequent Crash on item pickup

### ISSUE THREAD

**Issue by acemagex** [rolandoislas/multi-hotbar#29]
Have no idea what it is, unfortunately, other than that it seems to be from this mod.
[crash-2017-08-29_15.59.51-client.txt](https://github.com/rolandoislas/multi-hotbar/files/1261982/crash-2017-08-29_15.59.51-client.txt)

**Comment by rolandoislas** [comment]
The build bot should build and upload [v1.12-3.0-beta-2](https://github.com/rolandoislas/multi-hotbar/releases/tag/v1.12-3.0-beta-2) to CurseForge.
