### ISSUE TITLE
Major conflict with JEI?

### ISSUE THREAD

**Issue by Matakor** [rolandoislas/multi-hotbar#30]
So, prior to installing this mod, JEI worked fine. Now, for some weird reason (with custom inventory activated), everything in my inventory is a 'carrot', when I check recipes/uses.

I don't even have a carrot.

why is everything a carrot?

**Comment by rolandoislas** [comment]
The custom inventory is not fully implemented. Empty slots return a carrot to anything that requests its contents (I don't remember why). The slot returned is not translated to the custom order, so it will be the wrong slot given to JEI as well.
