### ISSUE TITLE
Opening inventory issue

### ISSUE THREAD

**Issue by sefldron** [rolandoislas/multi-hotbar#31]
I'm not sure if you know but the most recent version for 1.12 has a funny issue where if you are using a certain hotbar and open the inventory. I've noticed that the hotbar shows where the hotbar normally would of course but when sorting using inventory tweaks it will goof them up naturally. You should add a feature that will prevent sorting of an item stack from a slot the same way quark allows marking items to stay in the inventory during chest dumping. Would add great compatibility with inventory tweaks.

**Comment by sefldron** [comment]
Sorry title should have been sorting issue. My fault. I started typing this as I was noticing it. I'm going to mess with some things and see if there is a fix without you having to do anything.

**Comment by sefldron** [comment]
K well... nothing helped that. I imagine that alot of people who use this also use backpack mods and other inventory extension mods so the added feature would be useful. Besides this weird thing it's awesome. I just have to be careful when going into the inventory lol. Nice not having to open it up as much anymore.

**Comment by rolandoislas** [comment]
When switching hotbars the items in the hotbar, now deactivated, are swapped with the items from another inventory row, which is the active hotbar. This leaves the inventory state in a different order than is displayed on the hotbar. The custom inventory option remedies this to some extent, but it does not replicate all the features of the inventory with translated items. It is mostly for a visual improvement.

Note to self: Listen for InvTweaks sort event, set the inventory to the normal order, then set it back to the hotbar ordered state after InvTweaks has applied its modifications.

**Comment by sefldron** [comment]
That note to self would effectively sort the inventory temporarily while using it then revert back after exiting the inventory? That sounds useful..I only actually sort when I am moving things to a normal chest or machine anyway.

**Comment by rolandoislas** [comment]
It would allow Inventory Tweaks to sort the inventory normally in the hotbar view and in the custom inventory.
