### ISSUE TITLE
Items with GUIs Closed because of Reorder

### ISSUE THREAD

**Issue by sefldron** [rolandoislas/multi-hotbar#33]
With newest update there is an issue with opening a backpack from backpacks by right click inside the inventory with custom inventory mode on. I swear this mod is like right next to being perfect.

**Comment by sefldron** [comment]
I have not tested other "pack" type items yet. Eg: storage packs from thermal foundation

**Comment by sefldron** [comment]
Will craft one in a bit and check it out too. Sorry for multiple comments so quickly.

**Comment by ViriViri** [comment]
This also happens in the latest alpha with advanced shulker boxes: https://minecraft.curseforge.com/projects/advanced-shulkerboxes?gameCategorySlug=mc-mods&projectID=253861

**Comment by rolandoislas** [comment]
@ViriViri I have pushed new 3.1 beta and 3.2 alpha builds that fix the issue with advanced shulker boxes and other items that contain inventories.
