### ISSUE TITLE
Static Inventory

### ISSUE THREAD

**Issue by calloatti** [rolandoislas/multi-hotbar#34]
MC 1.12.1
multihotbar-1.12.1-3.1-build-T75

When opening the furnace GUI the top and bottom row are switched when the curent item is at the top row. 

Before:

![image](https://user-images.githubusercontent.com/12817862/30621415-52a14690-9d81-11e7-86da-36dff2a29e47.png)

Opening GUI, notice how rows switched:

![image](https://user-images.githubusercontent.com/12817862/30621427-638b8d58-9d81-11e7-8253-5b5da7f37885.png)

After. The top and bottom row are switched. Now the pick is selected. This also happens randomly all the time, cannot find a pattern as to why rows switch.

![image](https://user-images.githubusercontent.com/12817862/30621466-9d168d98-9d81-11e7-95a9-5e889acca56b.png)

**Comment by rolandoislas** [comment]
> In reply to [Bluesatin](https://minecraft.curseforge.com/projects/multi-hotbar?comment=41):
> In order to remain compatible with vanilla servers, when a hotbar is swapped, the contents of the active hotbar are put into the bottom row of the inventory and the contents that were there previously take the spot in the old row. The inventory gets jumbled as these swaps happen and there can not be a static order as the active hotbar is set to a specific row.
>
>The custom inventory fixes this slightly by rendering the items in a static order, taking the scrambling into consideration. The latest alpha build does not use a custom inventory and reorders correctly for the player inventory screen, but fails with any other container.
>
>Moving forward, I will be adding server-side handing when the mod is detected on a server (which will be always in the singleplayer integrated server). This will fix the jumbled inventory.

**Comment by calloatti** [comment]
Oh well, thank you for replying. This was not happening in the previous version (T71 I think).

I tried using the custom inventory, but it was emptying the Immersive Engineering crates in the inventory.

And yes, I am using it in single player.

**Comment by calloatti** [comment]
Your reply explained what I was seeing, and now I found the cause for the row swaps:

Here I have a portable grid currently selected on the top row:

![image](https://user-images.githubusercontent.com/12817862/30636892-1e914ee4-9dcd-11e7-9ddf-aeb1abb368c1.png)

When I right click to open the grid inventory, the rows get swapped, I understand why you do that, to keep compatibility with vanilla servers.

![image](https://user-images.githubusercontent.com/12817862/30636975-66042a44-9dcd-11e7-82ed-ff11914f4886.png)

Now when I close the portable grid inventory, the rows remain swapped:

![image](https://user-images.githubusercontent.com/12817862/30636992-744fa182-9dcd-11e7-8176-47234f3f8a96.png)

Couldn't you just keep track that you swapped the rows before showing any inventory GUI and swapping them back when the GUI is closed?

Another example with the wireless grid:

![image](https://user-images.githubusercontent.com/12817862/30637092-c8cbccf4-9dcd-11e7-820b-fd1e480e6499.png)

![image](https://user-images.githubusercontent.com/12817862/30637112-d369e3d0-9dcd-11e7-8cf9-e11f8b41fc5c.png)

![image](https://user-images.githubusercontent.com/12817862/30637136-def0662a-9dcd-11e7-90b2-f622d8723941.png)
