### ISSUE TITLE
Not compatible with BetterPvP_1.10.9_Forge_1.10.2

### ISSUE THREAD

**Issue by 7934345** [rolandoislas/multi-hotbar#4]
This mod block better pvp's funcion

and I really like these two mods.

**Comment by rolandoislas** [comment]
See commit d4d3344.

Unfortunately, BetterPvp seems to have bound to the **hotbar** render event. While fine in normal circumstances, it's elements to render are canceled when the default hotbar rendering is canceled.

I do not see a way around this and other mods that render HUD elements not relevant to the hotbar seem to render (e.g. JourneyMap, ToroHealth).

In summary, Multi-Hotbar cancels the vanilla hotbar rendering. Any mods that render their elements at this time (relevant to the hotbar or not) will also have those elements canceled.
