### ISSUE TITLE
Have to hit Tab twice to exit screens while cursor in second hotbar

### ISSUE THREAD

**Issue by madhatr** [rolandoislas/multi-hotbar#42]
As the title states, if the cursor/selector is in the second hot bar,  and screen that is opened up while in this state I need to hot Tab twice to escape that screen instead of just once like normal.

Examples,  chests, crafting table, machines from mods.

**Comment by rolandoislas** [comment]
In what version of Multi-Hotbar, Forge, and Minecraft is this encountered?

**Comment by madhatr** [comment]
woops, sorry forgot to add the version.
multihotbar-1.12.2-3.2-build-T96
1.12.2-forge1.12.2-14.23.0.2512

**Comment by rolandoislas** [comment]
I suggest upgrading to the 4.0 beta on downgrading to the 3.1 release.

**Comment by madhatr** [comment]
The beta 4.0 + core fixed the issue I was having, also a couple other ones.
