### ISSUE TITLE
Mod rejection on joining a server

### ISSUE THREAD

**Issue by trienow** [rolandoislas/multi-hotbar#43]
## What happened
On joining a server, which has the same Versions installed as on the client, I got disconnected with the error ```Mod rejections [FMLMod:multihotbar{1.12.2-4.0-build-T109}]```

A gist with the part of the log can be found here: https://gist.github.com/trienow/564ca8bcf8277645d77c8ff7addd1131

## Versions used
|       Item        |    Version     |
|-------------------|----------------|
| Minecraft         | 1.12.2           |
| Forge             | 14.23.0.2517   |
| Multi-Hotbar      | 4.0-build-T109 |
| Multi-Hotbar Core | 1.0-build-T20  |

**Comment by rolandoislas** [comment]
Multi-Hotbar, not the core mod, can be removed from the server. The issue will be fixed in the next build, but the main mod no longer has any server logic.

**Comment by trienow** [comment]
That did the trick. Thanks :)
