### ISSUE TITLE
Problem Glitch with mod

### ISSUE THREAD

**Issue by SirTwsted** [rolandoislas/multi-hotbar#46]
The mod is broken, if you place an item in the second bar, when scrolling with the mouse wheel, it continues way out of bounds.
The selection square continues further than its suppose to.
Its hard to explain.....  I will try to make a video of it, so you can see whats happening.

**Comment by SirTwsted** [comment]
I cant seem to find a way to upload a video some where without me having to create an account
and verifying email blah blah blah...
All I want to do is upload video so you can see whats happening, without me having to go through all the signing up to an account crap.
if you know of any please let me know.

**Comment by rolandoislas** [comment]
See #45.
