### ISSUE TITLE
TC auto-repair tool messes with item arrangement when moving between hotbars.

### ISSUE THREAD

**Issue by LaughingLeader** [rolandoislas/multi-hotbar#5]
**Minecraft Version:** 
- 1.7.10

**Modpack:** 
- [Sky Factory 2.5.5 (FTBPresentsSkyfactory25-2.5.5-1.7.10)](https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-2-5/files/2333326)

**Mod Versions:** 
- multihotbar-dev-17.jar
- TConstruct-1.7.10-1.8.8.jar
- IguanaTinkerTweaks-1.7.10-2.1.6.jar

**Bug:**

My Tinkers' Construct hatchet has auto-repair on it. When I lower the durability on it, and then it repairs itself to full durability, switching between the multi-hotbars screws up the order of items in my inventory.

When I open my inventory, the hatchet is on my cursor, as if I picked it up and am moving it. Once I place it somewhere, the hotbars go back to acting like normal.

I'm not sure if it's multi-hotbar that causes the issue, but once the bug happens, switching between the hotbars scatters my inventory items around. It should be reproducible, as I was able to trigger it every time my hatchet fully repaired itself.

**Comment by rolandoislas** [comment]
Note to self: The 10.1.2 branch item handling might fix this. Backport before investigating.

**Comment by rolandoislas** [comment]
I'm dropping 1.7.10 support.
