### ISSUE TITLE
Full Disabling of Unused Hotbars

### ISSUE THREAD

**Issue by Th4nat0s1s** [rolandoislas/multi-hotbar#52]
I would love to see where when you select say 2 hotbars it removes the other 2 completely so I dont have to scroll through two unused hotbars...
![2018-05-20_16 52 57](https://user-images.githubusercontent.com/25942971/40284093-1517e058-5c4f-11e8-869e-7b4145eb291f.png)

**Comment by Th4nat0s1s** [comment]
As you can see I am currently selecting an unused hotbar and it would nice to be able to just scroll through my two used hotbars.

**Comment by opencma** [comment]
Please post the version of Multi-Hotbar, Multi-Hotbar Core, and Forge.

**Comment by Th4nat0s1s** [comment]
Multi-Hotbar 1.12.2
Pre core? Using client side only?
1.12.2-forge1.12.2-14.23.3.2655

**Comment by Th4nat0s1s** [comment]
Nevermind, I updated to the most recent version and everything is amazing. Thanks for all your hard work!
