### ISSUE TITLE
Conflict with Cyclic Building Scepter and mode changing

### ISSUE THREAD

**Issue by Reignofmagic** [rolandoislas/multi-hotbar#57]
Not sure how you ping other developers (it has been a long time since I used Github sorry). 

But there appears to be a keybind/other conflict with cyclic. 

With only the following mods installed: Jei, Nei, Cyclic, and multi-hotbar. 
You are unable to use the shift scrollwheel function for cyclic's building scepter. This is because instead of switching modes, it switches inventory slots. 

I assume that this is due to something on the backend of multi-hotbar conflicting in the use of the shift key. This is due to the fact that as soon as multi-hot bar is removed from the modlist the problem goes away. 

Let me know if there is anything else I can help you with

**Comment by opencma** [comment]
Multi-Hotbar offers a toggle hotkey, a back-tick/tilde key by default.

**Comment by Reignofmagic** [comment]
Ah, using the "Default Hotbar" keybind fixed the conflict. 

I didn't know of that & I apparently missed that option in the keybinds section. Sorry for the clutter on the github!
