### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by abdullamu** [rolandoislas/multi-hotbar#8]
good day
i got this crash when i was breaking TC tool table to arrange them 

http://pastebin.com/BDXvgLWR

**Comment by rolandoislas** [comment]
What modpack was this?

**Comment by abdullamu** [comment]
ArdentCraft-The-Beginning

**Comment by MCJediYoda** [comment]
I am getting the same crash quite often.  It happens randomly with different items/ores.

http://pastebin.com/kPepj5rm
