### ISSUE TITLE
Can't light netherportal using flint in 2nd hotbar

### ISSUE THREAD

**Issue by xenoflot** [rolandoislas/multi-hotbar#9]
Weird!

multihotbar 1.10.2-2.0
forge 2185

**Comment by rolandoislas** [comment]
I can't reproduce the bug. More details might be necessary.

**Comment by xenoflot** [comment]
Weird. Definitely wasn't working for me earlier but I just tried again and it worked fine. Server has been rebooted in the mean time. /shrug 

I'll let you know if it becomes an issue. Thanks for the quick reply!
